### ISSUE TITLE
Can't open spool file on Ubuntu 18.04.1 LTS

### ISSUE THREAD

**Issue by blackketter** [HeyuX10Automation/heyu#18]
After a recent system update and reboot, heyu 2.10.1 seems to be having problems starting up with the following error:

HEYU: Can't open spool file /var/tmp/heyu/heyu.out.ttyUSB1

This was a previously working installation (for many years, thanks guys!) and I can't seem to figure out what's going on.  I've tried uninstalling and reinstalling heyu, system reboot, deleting and recreating /var/tmp/heyu all to no avail.

Any suggestions?

Thanks in advance.

**Comment by grahamdavies** [comment]
I am having exactly the same issue. Also Ubuntu 18.04.1 LTS with Heyu version 2.11-rc3.

HEYU: Can't open spool file /usr/local/var/tmp/heyu/heyu.out.ttyUSB0

uname -a gives:
Linux 4.15.0-44-generic #47-Ubuntu SMP Mon Jan 14 11:26:59 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

/dev/ttyUSB0 and /usr/loca/var/tmp/heyu/ both exist.

Using sudo doesn't help.

**Comment by heyu-users** [comment]
What happens if you rename the file 
/usr/local/var/tmp/heyu/heyu.out.ttyUSB0 and attempt to start it?

Tom Henderson

**Comment by blackketter** [comment]
/usr/local/var/tmp/heyu is empty, alas.

**Comment by blackketter** [comment]
To be clear:

 Both my /var/tmp/heyu and /usr/local/var/tmp/heyu directories are empty.  

My install seems to use /var/tmp/heyu (not /usr/local/var/tmp/heyu as @grahamdavies sees)

If I touch /var/tmp/heyu/heyu.out.ttyUSB1 and run heyu, the empty file is deleted and I see the error above.

**Comment by blackketter** [comment]
Also found this in /var/log/syslog:

Feb  2 21:46:54 monkey heyu_relay: relay setting up-
Feb  2 21:46:57 monkey heyu_relay: sxread() failed, error = Resource temporarily unavailable

**Comment by blackketter** [comment]
Ok, I got it to work with a little hack on my system.  In xread.c I disabled the versions of sxread() that use SIGACTION, SIGINTERRUPT or SIGKLUGE and just use the last one that is commented to be inaccurate with respect to timeouts.

The lights are back on in my house.  

Not sure what the correct fix is here, but happy to test any suggestions.

**Comment by ac00perw** [comment]
I can't get it to work and I'm not sure where config.h lives. 

heyu_relay: sxread() failed, error = Resource temporarily unavailable

**Comment by ac00perw** [comment]
I did find this which seems quite related:
https://unix.stackexchange.com/questions/459466/pl2303-pl2303x-usb-serial-driver

**Comment by heyu-users** [comment]
That can't be the problem for my situation, as the device I'm using has 
an FTDI chipset. I'm getting more and more convinced that this  has 
something to do with the lockfiles rather than the actual ttyUSB0 port. 
I just can't figure out what.

Tom Henderson

**Comment by blackketter** [comment]
For my situation the change I made definitely fixed it.   To try, follow the QuickStart instructions in the README:
```
Quickstart:
    sh ./Configure.sh [option] (As a normal user)
```
but stop here.  This should have created a file called  `config.h`. Edit this file and and delete the line that says:
```
#define HAVE_SIGACTION 1
```
Then continue with the rest of the instructions:
```
    make                       (As a normal user)
    su                         (Become superuser)
    make install 	       (As superuser)
    exit                       (Revert to normal user)
    heyu info		       (As a normal user, to test installation)
```
Let us know if this works for you...

**Comment by ivanxx** [comment]
Hi there! just having the same problem and tested your solution, but it's not working for me. I was on release 2.10 and now I'm 2.11-rc2 (it asked for 2 new folders I didn't have previously, though: /usr/local/var/tmp/heyu and /usr/local/var/lock). After creating and giving permissions, the sxread() error message appeared again... Ubuntu  16.04.5 LTS just updated today (oh my, this looks like one of these Windows update nightmares, only it's the first in my last 15 years of linux :-)

-Iván.

**Comment by ac00perw** [comment]
Funny, unless I'm daft and looking in the wrong place it didn't create a config.h file after sh ./Configure

I do see config.c and config.o

**Comment by heyu-users** [comment]
Thanks for the detailed instructions. Sadly, this did not work for me. 
Heyu compiled uising these instructions still works on 141 but not on 142.

Tom Henderson

**Comment by blackketter** [comment]
Is there anything in /var/log/syslog that might be related?

**Comment by ivanxx** [comment]
In my case, just this:
`Feb 10 12:45:20 zuncho heyu_relay: relay setting up-
Feb 10 12:45:23 zuncho heyu_relay: sxread() failed, error = Resource temporarily unavailable
`

**Comment by heyu-users** [comment]
I'll reboot into the new Kernel later today and let you know.

Tom Henderson

**Comment by heyu-users** [comment]
Here's what I got:

Feb 10 07:06:40 tom-desktop heyu_relay: relay setting up-
Feb 10 07:06:43 tom-desktop heyu_relay: sxread() failed, error = 
Resource temporarily unavailable
Feb 10 07:06:43 tom-desktop heyu_engine: engine setting up-
Feb 10 07:06:43 tom-desktop heyu_aux: aux setting up-
Feb 10 07:06:43 tom-desktop heyu_engine: interrupt received

Tom Henderson

**Comment by rgrokett** [comment]
I was able to get heyu_relay back running on my Ubuntu 16.04.5 LTS version.
4.4.0-142-generic #168-Ubuntu

Removed both signal lines from config.h 
This caused sxread() in xread.c to fall to a slower default mode of reading the ttyUSB0 port without using SIGALARM's but using millisecond sleeps, instead. (Thus slowing the read a fixed amount.)

#define HAVE_SIGACTION 1
#define HAVE_SIGINTERRUPT 1

Thanks to blackketter in narrowing down the problem. I just took it further by forcing the sxread() to not use any SIGALARM and it started working for me.   Hopefully 18.04 will be fixed with this as well...

Russell Grokett
WA4EFH

**Comment by ivanxx** [comment]
You are right Russell!! I tried ending with a 0 those #define lines instead of totally deleting them. I supposed a zero would invalidate them but now I guess my suppositions were wrong (and man I'm glad to be wrong!) 
Thank you so much, we're back in X10 business!

-Iván.

**Comment by ac00perw** [comment]
I screwed my head back in and got this to work. I had DL'd an older version of the source code. I git cloned this repo and commented out the proper lines and I'm back in business. 

Thanks you Heyu community for the help.

**Comment by grahamdavies** [comment]
I tried removing #define HAVE_SIGACTION 1 and #define HAVE_SIGINTERRUPT 1 lines and recompiling as suggested but this doesn't fix for me either. 

Here is the end of an strace of heyu info:

```
stat("/var/tmp/heyu/", {st_mode=S_IFDIR|0777, st_size=4096, ...}) = 0
stat("/var/lock/", {st_mode=S_IFDIR|S_ISVTX|0777, st_size=200, ...}) = 0
geteuid()                               = 1000
getgroups(30, [4, 20, 24, 27, 30, 44, 46, 100, 113, 129, 130, 1000]) = 12
stat("/var/lock/LCK..heyu.relay.ttyUSB0", 0x7ffc0b2bcc50) = -1 ENOENT (No such file or directory)
clone(child_stack=NULL, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7f0494535a10) = 32707
fstat(1, {st_mode=S_IFCHR|0620, st_rdev=makedev(136, 0), ...}) = 0
write(1, "starting heyu_relay\n", 20starting heyu_relay
)   = 20
nanosleep({tv_sec=3, tv_nsec=0}, 0x7ffc0b2bcd60) = 0
openat(AT_FDCWD, "/dev/ttyUSB0", O_RDWR|O_NONBLOCK) = 3
ioctl(3, TCGETS, 0x7ffc0b2bd070)        = -1 EIO (Input/output error)
socket(AF_UNIX, SOCK_DGRAM|SOCK_CLOEXEC, 0) = 4
connect(4, {sa_family=AF_UNIX, sun_path="/dev/log"}, 110) = 0
sendto(4, "<11>Feb 11 21:06:14 heyu: ttopen"..., 42, MSG_NOSIGNAL, NULL, 0) = 42
exit_group(1)                           = ?
+++ exited with 1 +++
```

Normal output gives:
```
↪ heyu info
starting heyu_relay
Can't open spool file: No such file or directory
HEYU: Can't open spool file /var/tmp/heyu/heyu.out.ttyUSB0
gpd at lazy in /v/log
↪ ls -l /var/tmp/heyu/
total 0
↪ uname -vr
4.15.0-45-generic #48-Ubuntu SMP Tue Jan 29 16:28:13 UTC 2019
↪ cat /etc/lsb-release
DISTRIB_DESCRIPTION="Ubuntu 18.04.2 LTS"
```

syslog shows:
```
Feb 11 21:06:14 lazy heyu: ttopen tcgetattr
Feb 11 21:07:50 lazy heyu_relay: relay setting up-
Feb 11 21:07:53 lazy heyu_relay: sxread() failed, error = Resource temporarily unavailable
```

**Comment by blackketter** [comment]
Update: After a power failure and reboot I found that I had to also comment out both the HAVE_SIGACTION and HAVE_SIGINTERRUPT interrupt lines to make it work again.  Weird.

**Comment by rgrokett** [comment]
> I tried removing #define HAVE_SIGACTION 1 and #define HAVE_SIGINTERRUPT 1 lines and recompiling as suggested but this doesn't fix for me either.
> 
> Feb 11 21:06:14 lazy heyu: ttopen tcgetattr
> Feb 11 21:07:50 lazy heyu_relay: relay setting up-
> Feb 11 21:07:53 lazy heyu_relay: sxread() failed, error = Resource temporarily unavailable
> ```

That still sounds like one or both of the two lines are still being picked up during compile time. 
Did you try a make clean, then just before doing a make again, verify that the config.h does not have the two SIG lines (Not 0, but actually removed.)  

Completely remove these two lines just before running make:

#define HAVE_SIGACTION 1
#define HAVE_SIGINTERRUPT 1

**Comment by jkrzyszt** [comment]
Hi,
For me it looks like if blocking mode for read() from a serial device was not working correctly with that Ubuntu kernel.  In both sigaction() and siginterrupt() based implementations of sxread(), read(fd, (char *)(buffer + nread), size - nread) should block for as long as a character is received from the port or an interrupted occurs from an alarm signal.  Instead, the function returns prematurely with -EAGAIN, that's why that "Resource temporarily unavailable" message appears and the serial port is recognized not working.
BTW, the so called kluge based implementation of sxread() is actually not used unless a user defines the SIGKLUGE symbol manually (Configure.sh doesn't handle it).  If my above analysis is correct, that method can't help much as sxread() will tend to return immediately with 0 characters read instead of waiting for a character.

The issue may be related to the following Ubuntu specific (not in official kernel 4.4 branch) kernel bug fix: https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1791758 .  It would be iiteresting to verify if newest kernel versions with the bug officially fixes also trigger that faulty behaviour of Heyu.

I may be able to tell more as soon as I get access to an environment where I can perform some testing.

Thanks,
Janusz

**Comment by jkrzyszt** [comment]
The issue with Ubuntu 18.04 kernel has been fixed, see https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1813873/comments/38 for details.
Thanks,
Janusz
