### ISSUE TITLE
Heyu engine and relay are not working anymore

### ISSUE THREAD

**Issue by TheFwGuy** [HeyuX10Automation/heyu#19]
After an update on my Ubuntu 16.04 Heyu is not working anymore.
When start with "sudo heyu start" it prints out starting heyu_relay and starting heyu_engine but the daemons are not running.
Issuing a command with heyu is not working.
For example :
sudo heyu -v on C1

Version:2.11-rc3
Searching for '/root/.heyu/x10config'
Searching for '/etc/heyu/x10.conf'
Found configuration file '/etc/heyu/x10.conf'
Heyu directory /etc/heyu/ is writable.
Reading Heyu configuration file '/etc/heyu/x10.conf'
lockpid: Checking for file '/var/lock/LCK..heyu.write.ttyS0'
Trying to lock (/var/lock/LCK..heyu.write.ttyS0)
lockpid: Checking for file '/var/lock/LCK..heyu.write.ttyS0'
/var/lock/LCK..heyu.write.ttyS0 is locked
Alert acks are 0x52, 0x12, 0x42
lockpid: Checking for file '/var/lock/LCK..heyu.relay.ttyS0'
Relay lockfile not found - spawning heyu_relay.
starting heyu_relay
Sending address bytes: 04 26

xwrite() called, count=2
xread() called, count=1, timeout = 1
Alarm - timeout
xread() returning 0 bytes
Checksum NOT confirmed, no response from interface
xwrite() called, count=2
xread() called, count=1, timeout = 1
Alarm - timeout
xread() returning 0 bytes
Checksum NOT confirmed, no response from interface
xwrite() called, count=2
xread() called, count=1, timeout = 1
Alarm - timeout
xread() returning 0 bytes
Checksum NOT confirmed, no response from interface
Unable to send address bytes

lockpid: Checking for file '/var/lock/LCK..heyu.write.ttyS0'

I did try to  set up a systemd entry, it seems to work but no daemon are present.
I set up a entry for heyu in /etc/systemd/system/heyu.service

[Unit]
Description=Heyu Engine
Wants=network.target
After=network.target

[Service]
Type=oneshot
RemainAfterExit=yes
User=aaaaa
Group=
WorkingDirectory=/home/aaaa
ExecStart=/usr/local/bin/heyu start
ExecReload=/usr/local/bin/heyu restart
ExecStop=/usr/local/bin/heyu stop

[Install]
WantedBy=multi-user.target

Then enabled and started and status

sudo systemctl enable heyu.service
Synchronizing state of heyu.service with SysV init with /lib/systemd/systemd-sysv-install...
Executing /lib/systemd/systemd-sysv-install enable heyu

sudo systemctl start heyu.service

sudo systemctl status heyu.service
● heyu.service - Heyu Engine
   Loaded: loaded (/etc/systemd/system/heyu.service; enabled; vendor preset: enabled)
   Active: active (exited) since Mon 2019-02-04 18:18:46 CST; 5s ago
  Process: 22207 ExecStart=/usr/local/bin/heyu start (code=exited, status=0/SUCCESS)
 Main PID: 22207 (code=exited, status=0/SUCCESS)
    Tasks: 0
   Memory: 196.0K
      CPU: 5ms
   CGroup: /system.slice/heyu.service

Feb 04 18:18:43 opus systemd[1]: Starting Heyu Engine...
Feb 04 18:18:46 opus systemd[1]: Started Heyu Engine.

But still no daemon running and heyu is not working

How to solve that ? Any clue ?  Thanks

**Comment by bajax** [comment]
I had a similar problem.  The solution was to delete the heyu lock files located at (in my case) `/usr/local/var/lock/`.

Apparently, heyu had been killed at some point without being able to clear its lock files (which seem to be how it tells whether the daemon is running).  It seems like heyu checks for those to determine whether to start the relay.  A more helpful error message such as "heyu appears to already be running" would more quickly point end users to the actual issue rather than faking us out that it thinks everything's alright.

**Comment by jkrzyszt** [comment]
The issue with Ubuntu 16.04 kernel has been fixed, see https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1813873/comments/21 for details.
Thanks,
Janusz
