### ISSUE TITLE
Upload failed to write block

### ISSUE THREAD

**Issue by ikolinahr** [HeyuX10Automation/heyu#20]
I have been using Heyu successfully for years. I recently moved to a new computer and all heyu commands that I have tried work without fail except for upload. It always fails on this computer around blocks 57 to 60. I would think that this is a timing problem as the new computer is considerably faster than the old one. I tried 'heyu utility calibrate' and that only seemed to make things worse.

**Comment by jkrzyszt** [comment]
First of all, sorry for missing this request.  Github notifications don't work very stabily for me, sometimes I get them, sometimes not.

I believe this issue is a duplicate of #22 .
