### ISSUE TITLE
Building with -fno-common fails

### ISSUE THREAD

**Issue by finagolfin** [HeyuX10Automation/heyu#26]
This matters because both [gcc 10](https://gcc.gnu.org/gcc-10/porting_to.html) and [clang 11](https://releases.llvm.org/11.0.0/tools/clang/docs/ReleaseNotes.html#modified-compiler-flags) have switched to applying that flag by default. If I pass it in manually to gcc 9.3.0 by running `CFLAGS=-fno-common ./Configure.sh && make`, I get this at the end:
```
gcc  -fno-common   -o heyu heyu-date.o heyu-erase.o heyu-info.o heyu-message.o heyu-relay.o heyu-monitor.o heyu-reset.o heyu-setclock.o heyu-stop.o heyu-tty.o heyu-x10.o heyu-xread.o heyu-xwrite.o heyu-status.o heyu-cm11a.o heyu-eeprom.o heyu-process.o heyu-sun.o heyu-cmd.o heyu-config.o heyu-x10state.o heyu-poll.o heyu-modules.o heyu-cm17a.o heyu-xsync.o heyu-timing.o heyu-cm10a.o heyu-tty_aux.o heyu-relay_aux.o heyu-x10aux.o heyu-rfxcom.o heyu-digimax.o heyu-oregon.o heyu-xpl.o  -lm
/usr/bin/ld: heyu-tty_aux.o:(.bss+0x0): multiple definition of `oldsb'; heyu-tty.o:(.bss+0x0): first defined here
/usr/bin/ld: heyu-tty_aux.o:(.bss+0x40): multiple definition of `newsb'; heyu-tty.o:(.bss+0x40): first defined here
/usr/bin/ld: heyu-relay_aux.o:(.bss+0x0): multiple definition of `spoolfile'; heyu-relay.o:(.bss+0x0): first defined here
collect2: error: ld returned 1 exit status
```

**Comment by vmummer** [comment]
make CFLAGS='-fcommon'   

Fixes it

**Comment by finagolfin** [comment]
Of course, but since this is becoming the default in both gcc and clang, it would be better if it were fixed in the code instead.

**Comment by jkrzyszt** [comment]
Should be now fixed in 'testing' branch, please test.

**Comment by jkrzyszt** [comment]
The gcc 10+ fix has been backported to 'stable' branch. Closing as resolved.
