### ISSUE TITLE
Unable to compile using gcc 10.2.1

### ISSUE THREAD

**Issue by bdbogjoe** [HeyuX10Automation/heyu#27]
here the log  :

gcc  -g -O2 -Wall   -o heyu heyu-date.o heyu-erase.o heyu-info.o heyu-message.o heyu-relay.o heyu-monitor.o heyu-reset.o heyu-setclock.o heyu-stop.o heyu-tty.o heyu-x10.o heyu-xread.o heyu-xwrite.o heyu-status.o heyu-cm11a.o heyu-eeprom.o heyu-process.o heyu-sun.o heyu-cmd.o heyu-config.o heyu-x10state.o heyu-poll.o heyu-modules.o heyu-cm17a.o heyu-xsync.o heyu-timing.o heyu-cm10a.o heyu-tty_aux.o heyu-relay_aux.o heyu-x10aux.o heyu-rfxcom.o heyu-digimax.o heyu-oregon.o heyu-xpl.o  -lm 
/usr/bin/ld : heyu-tty_aux.o:/home/eric/domotique/heyu/tty_aux.c:142 : définitions multiples de « oldsb »; heyu-tty.o:/home/eric/domotique/heyu/tty.c:137 : défini pour la première fois ici
/usr/bin/ld : heyu-tty_aux.o:/home/eric/domotique/heyu/tty_aux.c:142 : définitions multiples de « newsb »; heyu-tty.o:/home/eric/domotique/heyu/tty.c:137 : défini pour la première fois ici
/usr/bin/ld : heyu-relay_aux.o:/home/eric/domotique/heyu/relay_aux.c:98 : définitions multiples de « spoolfile »; heyu-relay.o:/home/eric/domotique/heyu/relay.c:103 : défini pour la première fois ici
collect2: erreur: ld a retourné le statut de sortie 1
make[1]: *** [Makefile:434: heyu] Error 1

**Comment by vmummer** [comment]
I am seeing the same issue. 

Did you have a resolution?

V

**Comment by vmummer** [comment]
make CFLAGS='-fcommon'


Fixed the issue,

**Comment by jkrzyszt** [comment]
Should be now fixed in 'testing' branch, please test.

**Comment by jkrzyszt** [comment]
Closing as a duplicate of #26 .
