### ISSUE TITLE
Heyu 2.10.3

### ISSUE THREAD

**Issue by yvesbbbb** [HeyuX10Automation/heyu#37]
The heyu monitor traces all x10 events (on, off)  but some devices cannot be controlled with the usual commands.

 ex: heyu on a2, heyu off a2

**Comment by jkrzyszt** [comment]
That doesn't sound like a software issue to me.  Please check your hardware.
Also, run your commands with -v option for verbose output and report if you see any error messages.

Hardware issues can be discussed under Discussions.
