### ISSUE TITLE
Problems Building Heyu 2.11-rc1 On Ubuntu 16 on AML S905 TV Computer

### ISSUE THREAD

**Issue by whitedavidp** [HeyuX10Automation/heyu#4]
The configure program complained about guess. I was able to find and install the two updated files used for guess and all is well. I tried to attach them in a .zip here but it just would not work. Perhaps this is fixed in rc2 but I was sticking with the old standard that has served me for years.

**Comment by jkrzyszt** [comment]
Hi,

Could you please have a look at pull request #5, download a snapshot and verify if it fixes the problem for you?

Thanks,
Janusz

**Comment by jkrzyszt** [comment]
Please download the snapshot from https://github.com/HeyuX10Automation/heyu/archive/cf85f5331ceb21e8836d7a52db438df2a9a38df6.zip

Thanks,
Janusz

**Comment by whitedavidp** [comment]
The ./configure step now completes fine. I think you nailed it. Thanks
