### ISSUE TITLE
Heyu 2.10.3 (also: how to resolve issues with file permissions / group ownership of device file and/or lock directory -- any Heyu version)

### ISSUE THREAD

**Issue by vvstubbs** [HeyuX10Automation/heyu#44]
Even if I run from the root account it reports can't create file in /var/lock/LCK..LCK.. the directory has lock file in it not only from root but other user accounts

### Discussed in https://github.com/HeyuX10Automation/heyu/discussions/36

<div type='discussions-op-text'>

<sup>Originally posted by **jkrzyszt** April 30, 2021</sup>
#### List of changes since release 2.10.2:

Fredrik Fornwall (1):
      Replace rindex(3) with strrchr(3)

Janusz Krzysztofik (2):
      Fix gcc 10+ build errors
      Heyu 2.10.3

#### [Changelog](http://github.com/HeyuX10Automation/heyu/compare/v2.10.2...v2.10.3) against last stable release 2.10.2

<hr /><em>This discussion was created from the release <a href='https://github.com/HeyuX10Automation/heyu/releases/tag/v2.10.3'>Heyu 2.10.3</a>.</em></div>

**Comment by jkrzyszt** [comment]
Duplicates #25
