### ISSUE TITLE
Bug in show ore with rain sensor

### ISSUE THREAD

**Issue by meteo-29** [HeyuX10Automation/heyu#6]
Hello,

While testing a rain sensor (known as ORE_RAIN2 in heyu), I noticed a bug in the return of "heyu show ore" command.

In the monitor I had these values:

2017/07/13 13:35:57  rcva func  oreRainRate : hu D2  Ch 1 Rate
4.58inches/hr (PLUVIO)
2017/07/13 13:35:57  rcva func   oreRainTot : hu D2  Ch 1 TotRain
0.20inches (PLUVIO)

Then I removed the batteries and had the idea to run "show ore", and I got this:
D2  ORE_RAIN2 PLUVIO    Ch 1 Rate 4.58inches/hr Total 4.58inches

It looks like it does not take the right value to display the Total Rain.
I was expecting to have: 
D2  ORE_RAIN2 PLUVIO    Ch 1 Rate 4.58inches/hr Total 0.20inches

Someone else can confirm this bug?

Regards,

**Comment by jkrzyszt** [comment]
Fixed by #7
